version: 0.0
os: linux
files:
  - source: ./build_output
    destination: /home/ubuntu/bingoapp
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/bingoapp
  - source: scripts/kestrel-aspnetcoreapp.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore.sh
      timeout: 500
      runas: root

    - location: scripts/install_httpd.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
  # q