version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - pip install --upgrade awscli
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output projAspAngular/WebSocket.csproj
      - dotnet publish -c release -o ./test_output Bingo.Application.Test/Bingo.Application.Test.csproj

artifacts:
  files:
    - ./build_output/**/*
    - scripts/**/*
    - AppSpec.yml
