// <auto-generated />
using Bingo.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bingo.Infraestructura.Migrations
{
    [DbContext(typeof(BingoContext))]
    partial class BingoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Bingo.Domain.Entities.Carton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("JugadorID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cartones");
                });

            modelBuilder.Entity("Bingo.Domain.Entities.Carton", b =>
                {
                    b.OwnsMany("Bingo.Domain.ValueObjects.Casilla", "Casillas", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("CartonId")
                                .HasColumnType("int");

                            b1.Property<bool>("Marcado")
                                .HasColumnType("tinyint(1)");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("CartonId");

                            b1.ToTable("Casilla");

                            b1.WithOwner()
                                .HasForeignKey("CartonId");

                            b1.OwnsOne("Bingo.Domain.ValueObjects.Coordenada", "coordenada", b2 =>
                                {
                                    b2.Property<int>("CasillaId")
                                        .HasColumnType("int");

                                    b2.Property<int>("posX")
                                        .HasColumnType("int");

                                    b2.Property<int>("posY")
                                        .HasColumnType("int");

                                    b2.HasKey("CasillaId");

                                    b2.ToTable("Casilla");

                                    b2.WithOwner()
                                        .HasForeignKey("CasillaId");
                                });

                            b1.Navigation("coordenada");
                        });

                    b.Navigation("Casillas");
                });
#pragma warning restore 612, 618
        }
    }
}
